language: node_js
node_js:
  - node

notifications:
  email:
    on_success: never
    on_failure: change

cache: yarn

script:
  - npm run coverage
  - npm run coveralls

jobs:
  fast_finish: true

services:
  - docker
