language: node_js
node_js:
  - node

notifications:
  email:
    on_success: never
    on_failure: change

cache: yarn

before_script: yarn build

script:
  - yarn coverage
  - yarn coveralls

jobs:
  fast_finish: true

services:
  - docker
