name: CI

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Coverage
      run: yarn coverage

    - name: Coveralls
      run: yarn coveralls

