name: CI

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: yarn

    - name: Build WASM
      run: yarn build

    - name: Coverage
      run: yarn coverage

    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2

